# Generated by Django 4.0.2 on 2022-03-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_picture_alter_listing_picture_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture_text',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
